export default {
    pt: [
        {
            title:       "Desenvolvedor Full-stack",
            company:     "Visie Padrões Web",
            date:        "Mai. 2021 - ATUAL",
            description: "Trabalho no desenvolvimento de uma carteira digital.",
            link:        "https://visie.com.br/",
            skills:      ["PHP", "Postgres", "Elixir", "API", "RabbitMQ"],
            show:        true,
        },
        {
            title:       "Website para E-commerce",
            company:     "Freelance",
            date:        "Mar. 2020 - Mai. 2020",
            description: "Desenvolvimento de um e-commerce para uma ótica contendo controle de estoque, página de administração e comunicação com as APIs do PagSeguro, para pagamentos online, e dos Correios, para entrega de mercadorias.",
            link:        "https://oticaportuguesa.com",
            skills:      ["PHP", "MySQL", "JQuery", "Bootstrap 4"],
            show:        true,
        },
        {
            title:       "Website Next.js",
            company:     "Freelance",
            date:        "Abr. 2021 - ATUAL",
            description: "Está sendo desenvolvido um website pessoal (blog), para um cliente, contendo uma API REST no back-end, contato de suporte em tempo real, autenticação, envio de e-mails e postagens.",
            link:        "https://github.com/Nicolasbort/Nextjs-website",
            skills:      ["Next.js", "React", "MongoDB", "Bootstrap 5", "API"],
            show:        true,
        },
        {
            title:       "Chat Online em Tempo Real",
            company:     "Projeto de Faculdade",
            date:        "Abr. 2021 - Abr. 2021",
            description: "Desenvolvimento de um chat online, em conjunto com <a href='https://github.com/iagobalmeida'>Iago Almeida</a>, aplicando os conceitos de cliente-servidor, que permite comunicação em tempo real de maneira privada, em grupo ou com todos conectados. Além disso, permite criar grupos e adicionar contatos.",
            link:        "https://github.com/Nicolasbort/Chat-nodejs",
            skills:      ["Node.js", "Vue.js", "Socket.io", "Bootstrap 5"],
            show:        true,
        },
        {
            title:       "Portfólio de Criptomoedas",
            company:     "Projeto Pessoal",
            date:        "Fev. 2021 - ATUAL",
            description: "Desenvolvendo um portfólio de criptomoedas com o intuito de gerenciar de maneira fácil e ágil as fincanças. Futuramente será possível realizar saque, compra e venda de ativos, além de permitir ver em tempo real suas informações. Além disso, para obter e enviar as informações, a API da Binance está sendo usada.",
            link:        "https://github.com/Nicolasbort/Crypto-porfolio-nodejs",
            skills:      ["Node.js", "Vue.js", "Socket.io", "Bootstrap 5", "API"],
            show:        true,
        },
        {
            title:       "Escalonador de Processos",
            company:     "Projeto de Faculdade",
            date:        "Jul. 2019 - Dez. 2019",
            description: "Foi desenvolvido um simulador de escalonamento de processos de sistemas operacionais contendo os algoritmos Round-Robin, First-In First-Out (FCFS) e Shortest Job First (SJF).",
            link:        "https://github.com/Nicolasbort/Process-Scheduler",
            skills:      ["JavaScript", "CSS"],
            show:        true,
        },
        {
            title:       "Jogo 2D",
            company:     "Projeto de Faculdade",
            date:        "Jul. 2018 - Dez. 2018",
            description: "Primeiro projeto desenvolvido na faculdade. Nesse projeto foi desenvolvido um jogo de futebol 2D para dois jogadores no mesmo computador. Foi utilizado conteitos de álgebra linear, além de outras áreas",
            link:        "https://github.com/Nicolasbort/Old-Head-Soccer",
            skills:      ["Python"],
            show:        true,
        },

    ],

    en: [
        {
            title:       "Full-stack developer",
            company:     "Visie Padrões Web",
            date:        "May. 2021 - PRESENT",
            description: "Developed a microservice using Elixir and RabbitMQ. The microservice is responsible for registering deposits, refunds and withdrawals,
            link:        "https://visie.com.br/",
            skills:      ["PHP", "Postgres", "Elixir", "API", "RabbitMQ"],
            show:        true,
        },
        {
            title:       "E-commerce Website",
            company:     "Freelance",
            date:        "Mar. 2020 - May 2020",
            description: "Developed an E-Commerce website for an eyeglasses store containing inventory control, administration page and communication with PagSeguro and Post Office APIs, in order to manage online payments and delivery of goods, respectively.",
            link:        "https://oticaportuguesa.com",
            skills:      ["PHP", "MySQL", "JQuery", "Bootstrap 4"],
            show:        true,
        },
        {
            title:       "Next.js Website",
            company:     "Freelance",
            date:        "Apr. 2020 - PRESENT",
            description: "Developing a personal website (blog), containing an API in the back-end. Besides that, the also application allows: authentication, create posts, real-time support contact and send emails.",
            link:        "https://github.com/Nicolasbort/Nextjs-website",
            skills:      ["Next.js", "React", "MongoDB", "Bootstrap 5", "API"],
            show:        true,
        },
        {
            title:       "Real-Time Chat Application",
            company:     "College Project",
            date:        "Apr. 2021 - Apr. 2021",
            description: "Developed a online chat, together with <a href='https://github.com/iagobalmeida'>Iago Almeida</a>, applying the knowledge about client-server applications, that allows real-time communication privately, in groups and with everyone connected.",
            link:        "https://github.com/Nicolasbort/Chat-nodejs",
            skills:      ["Node.js", "Vue.js", "Socket.io", "Bootstrap 5"],
            show:        true,
        },
        {
            title:       "Cryptocurrency Portfolio",
            company:     "Personal Project",
            date:        "Feb. 2021 - PRESENT",
            description: "Developing a cryptocurrency portfolio in order to easily and quickly manage finances. In the future, the application will allow withdrawals, purchases and sales of assets.",
            link:        "https://github.com/Nicolasbort/Crypto-porfolio-nodejs",
            skills:      ["Node.js", "Vue.js", "Socket.io", "Bootstrap 5", "API"],
            show:        true,
        },
    ]
}